CREATE OR REPLACE VIEW V_ESTOQUE AS 
  SELECT E1.IDEQUIPAMENTO, 
         E1.DATAESTOQUE, 
         E1.ENTRADAS, 
         E1.SAIDAS, 
         E1.RESERVAS,         
         SUM(COALESCE(E1.ENTRADAS,0)) 
         	OVER (PARTITION BY E1.IDEQUIPAMENTO ORDER BY E1.DATAESTOQUE) TOTENTRADAS,   
         	
         SUM(COALESCE(E1.SAIDAS,0))  
         	OVER (PARTITION BY E1.IDEQUIPAMENTO ORDER BY E1.DATAESTOQUE) TOTSAIDAS,  
         	
         SUM(COALESCE(E1.RESERVAS,0))  
         	OVER (PARTITION BY E1.IDEQUIPAMENTO ORDER BY E1.DATAESTOQUE) TOTRESERVAS,	
         	
         SUM(COALESCE(E1.ENTRADAS,0)) 
         	OVER (PARTITION BY E1.IDEQUIPAMENTO ORDER BY E1.DATAESTOQUE) -
         SUM(COALESCE(E1.SAIDAS,0)) 
         	OVER (PARTITION BY E1.IDEQUIPAMENTO ORDER BY E1.DATAESTOQUE) -
     	SUM(COALESCE(E1.RESERVAS,0)) 
    	 	OVER (PARTITION BY E1.IDEQUIPAMENTO ORDER BY E1.DATAESTOQUE) AS SALDO
    FROM ESTOQUE E1        
   ORDER BY E1.IDEQUIPAMENTO, E1.DATAESTOQUE DESC;